version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://mongo:27017/organizations
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
      - mongo_config:/data/config

volumes:
  mongo:
  mongo_config: